pipeline{
    agent {
        label 'azure-collider-vm'
    }

    stages{
        stage('build'){
            steps{
                sh '''
                ls
                cd code-collab-compiler-backend
                ls
                cd code-collab-compiler-backend/code-collab
                mvn clean install
                '''
            }
        }
        stage('deploy'){
            steps{
                sh '''
                    ls
                    cd target
                    ls
                    cp code-collab.jar /home/collider-backend/
                '''
            }
        }
    }
}